#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/scs_dev
#    username: scs_user
#    password: scs_pass
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#logging:
#  level:
#    com.pharmacy.scs: DEBUG
#    org.hibernate.SQL: DEBUG